CREATE DATABASE IF NOT EXISTS tour_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tour_db;

CREATE TABLE IF NOT EXISTS cities (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS categories (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  parent INT UNSIGNED DEFAULT NULL,
  position INT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'active',
  avatar VARCHAR(500) DEFAULT '',
  description TEXT,
  slug VARCHAR(255) NOT NULL UNIQUE,
  created_by INT UNSIGNED DEFAULT NULL,
  updated_by INT UNSIGNED DEFAULT NULL,
  deleted TINYINT(1) DEFAULT 0,
  deleted_at DATETIME DEFAULT NULL,
  deleted_by INT UNSIGNED DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tours (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(500) NOT NULL,
  category INT UNSIGNED DEFAULT NULL,
  position INT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'active',
  avatar VARCHAR(500) DEFAULT '',
  images JSON,
  price_adult DECIMAL(15,2) DEFAULT 0,
  price_children DECIMAL(15,2) DEFAULT 0,
  price_baby DECIMAL(15,2) DEFAULT 0,
  price_new_adult DECIMAL(15,2) DEFAULT 0,
  price_new_children DECIMAL(15,2) DEFAULT 0,
  price_new_baby DECIMAL(15,2) DEFAULT 0,
  stock_adult INT DEFAULT 0,
  stock_children INT DEFAULT 0,
  stock_baby INT DEFAULT 0,
  locations JSON,
  destination JSON,
  time VARCHAR(100) DEFAULT '',
  vehicle VARCHAR(255) DEFAULT '',
  departure_date DATE DEFAULT NULL,
  information LONGTEXT,
  schedules JSON,
  created_by INT UNSIGNED DEFAULT NULL,
  updated_by INT UNSIGNED DEFAULT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  deleted TINYINT(1) DEFAULT 0,
  deleted_by INT UNSIGNED DEFAULT NULL,
  deleted_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS roles (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  permissions JSON,
  created_by INT UNSIGNED DEFAULT NULL,
  updated_by INT UNSIGNED DEFAULT NULL,
  deleted TINYINT(1) DEFAULT 0,
  deleted_at DATETIME DEFAULT NULL,
  deleted_by INT UNSIGNED DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS accounts_admin (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(50) DEFAULT '',
  role INT UNSIGNED DEFAULT NULL,
  position_company VARCHAR(255) DEFAULT '',
  status VARCHAR(20) DEFAULT 'initial',
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR(500) DEFAULT '',
  created_by INT UNSIGNED DEFAULT NULL,
  updated_by INT UNSIGNED DEFAULT NULL,
  deleted TINYINT(1) DEFAULT 0,
  deleted_at DATETIME DEFAULT NULL,
  deleted_by INT UNSIGNED DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  note TEXT,
  items JSON NOT NULL,
  sub_total DECIMAL(15,2) DEFAULT 0,
  discount DECIMAL(15,2) DEFAULT 0,
  total DECIMAL(15,2) DEFAULT 0,
  payment_method VARCHAR(50) DEFAULT 'money',
  payment_status VARCHAR(20) DEFAULT 'unpaid',
  status VARCHAR(20) DEFAULT 'initial',
  updated_by INT UNSIGNED DEFAULT NULL,
  deleted TINYINT(1) DEFAULT 0,
  deleted_at DATETIME DEFAULT NULL,
  deleted_by INT UNSIGNED DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS contacts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  deleted TINYINT(1) DEFAULT 0,
  deleted_by INT UNSIGNED DEFAULT NULL,
  deleted_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS setting_website_info (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  website_name VARCHAR(255) DEFAULT 'Tour Travel',
  phone VARCHAR(50) DEFAULT '',
  email VARCHAR(255) DEFAULT '',
  address TEXT,
  logo VARCHAR(500) DEFAULT '/assets/images/logo.png',
  favicon VARCHAR(500) DEFAULT '',
  category_id_section4 INT UNSIGNED DEFAULT NULL,
  category_id_section6 INT UNSIGNED DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS forgot_password (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  otp VARCHAR(10) NOT NULL,
  expire_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

